version: "3.3"
services:
  dyndns_python:
    build: .
    container_name: dyndns
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - .:/code
    restart: unless-stopped
